// Code generated by mockery v2.23.1. DO NOT EDIT.

package mocks

import (
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"

	user "github.com/ALTA-PROJECT3-GROUP3/EventPlanningApp-BE/feature/user"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// DeleteUserLogic provides a mock function with given fields: id
func (_m *UseCase) DeleteUserLogic(id uint) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LogInLogic provides a mock function with given fields: username, password
func (_m *UseCase) LogInLogic(username string, password string) (user.Core, error) {
	ret := _m.Called(username, password)

	var r0 user.Core
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (user.Core, error)); ok {
		return rf(username, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) user.Core); ok {
		r0 = rf(username, password)
	} else {
		r0 = ret.Get(0).(user.Core)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterUser provides a mock function with given fields: newUser
func (_m *UseCase) RegisterUser(newUser user.Core) error {
	ret := _m.Called(newUser)

	var r0 error
	if rf, ok := ret.Get(0).(func(user.Core) error); ok {
		r0 = rf(newUser)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateProfileLogic provides a mock function with given fields: id, name, email, password, picture
func (_m *UseCase) UpdateProfileLogic(id uint, name string, email string, password string, picture *multipart.FileHeader) error {
	ret := _m.Called(id, name, email, password, picture)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, string, string, string, *multipart.FileHeader) error); ok {
		r0 = rf(id, name, email, password, picture)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserProfileLogic provides a mock function with given fields: id
func (_m *UseCase) UserProfileLogic(id uint) (user.Core, error) {
	ret := _m.Called(id)

	var r0 user.Core
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (user.Core, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) user.Core); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(user.Core)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUseCase(t mockConstructorTestingTNewUseCase) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
